### ISSUE TITLE
Will someone please think of the children

### ISSUE THREAD

**Issue by Fweddi** [FAC-Sixteen/Week6-project-Onions#25]
Just wondering what lines 8-10 in script.js do?

`while(tableToFill.childNodes[2]) {
            tableToFill.removeChild(tableToFill.childNodes[2])
        };`

**Comment by sylv1ah** [comment]
this clears our opinions table every time an action point is clicked so that the opinions table wouldn't concat every time an action is clicked (so it checks if out table has a second childNode if it does then it will remove them)

*DISCLAIMER* no children were harmed during the development of our app
